### ISSUE TITLE
PlatformIO version: TNFS Host List error after second host directory listing

### ISSUE THREAD

**Issue by jeffpiep** [FujiNetWIFI/atariwifi#121]
Immediately after listing a TNFS directory for the second time, the ESP32 thinks it receives the SIO command CF: 00 00 00 52 6a, which is invalid. It should be CF: 70 f4 ..... sio_read_hosts_slots();

**Comment by tschak909** [comment]
I did discover a timing error on ESP32, where the T4 delay MUST be used, otherwise, the OS mistakes a  COMPLETE for an ACK.

-Thom

**Comment by jeffpiep** [comment]
DELAY_T4 fixed part of the problem. The invalid command is not longer received. However, the following actions in CONFIG repeat the error:

1. boot and attached to Wifi
2. Pick a TNFS server
3. ESC out after listing is complete
4. Pick a TNFS server

CONFIG immediately tries to return to the TNFS server list but does not ask the ESP for a list of hosts.

**Comment by tschak909** [comment]
Yes, verified, and i'm trying to figure out where and how this regression creeped in.

**Comment by tschak909** [comment]
fixed.
