### ISSUE TITLE
[platformio] Conflict between FujiNet and non-Fujinet devices.

### ISSUE THREAD

**Issue by tschak909** [FujiNetWIFI/atariwifi#129]
1. With FujiNet and drive connected, Power off disk drive. Power on Atari
2. Boot into CONFIG.
3. Remove all device slots.
4. Power on disk drive.
5. OPTION.

The 1050 drive and FujiNet subsequently try to answer status and reads, causing NAKs.

**Comment by mozzwald** [comment]
This should be fixed with commit 535fd84. @tschak909 you confirmed this, correct?

**Comment by tschak909** [comment]
Confirmed. Yup, closing.
