### ISSUE TITLE
FNEW: File created, mounted in drive slot, unable to format. Error-144.

### ISSUE THREAD

**Issue by FujiMan66** [FujiNetWIFI/atariwifi#157]
DOS 2.5 in drive 1. FNC-Tools in 2. D3: is the target.
Using FNEW, created new single density ATR and put into drive slot 3. Formatting ATR resulted in Error-144.
Possible that ATR was not writable after creation.
Remounting DOS, FNC-Tool, and then ATR write enabled in D3: Allowed formatting.
After formatting the file size grew from 91kb to 129kb.

**Comment by tschak909** [comment]
Fixed.
