### ISSUE TITLE
TNFS Host / Drive Slot menu always ejects D1 first

### ISSUE THREAD

**Issue by FujiMan66** [FujiNetWIFI/atariwifi#164]
After loading all 8 drive slots, any slot selected will eject slot 1 when it should be the selected slot.

**Comment by tschak909** [comment]
I would ask for a set of steps that can be done to consistently reproduce the bug, if possible. It will allow me to narrow down the problem, and construct a unit test. :)

**Comment by FujiMan66** [comment]
I load atrs into drive 1-x. I want to delete drive slot 3, I press 3 and D3: is selected. Pressing E for eject, ejects D1: (not D3: as selected). Doesn't matter which one is selected, D1: is ejected the first time, not the drive selected. Subsequent ejects work properly.
