### ISSUE TITLE
Welcome to FujiNet screen

### ISSUE THREAD

**Issue by savetz** [FujiNetWIFI/atariwifi#79]
The "Welcome to FujiNet / Connecting to Net" screen is a bit confusing:

1) It's unclear that all you need to do here is wait. It shows what network it's connecting to, but it looks like it is prompting you to choose your network from a (short) list of networks. So I press RETURN.

2) ... and when it gets to the TNFS Host List screen, it immediately opens the #1 host, because I pressed RETURN on the previous screen. It should clear the keyboard buffer going into this screen.

**Comment by tschak909** [comment]
Awaiting Verification
